service: purescript-aws-lambda-express-test

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  # stage: ${opt:stage dev}
  region: eu-west-2

functions:
  lambda:
    handler: output/Main/index.handler
    events:
      - http:
          path: / # this matches the base path
          method: ANY
      - http:
          path: /{any+}
          method: ANY
